version: '3'
services:
  substrate:
    image: docker.pkg.github.com/astarnetwork/zkrollups/substrate:latest
    container_name: substrate
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"
      - "5000:5000"
      - "6000:6000"
  test:
    image: docker.pkg.github.com/astarnetwork/zkrollups/test:latest
    container_name: test
    tty: true
    stdin_open: true
    env_file:
      - ./env/integration.env
  setup:
    image: docker.pkg.github.com/astarnetwork/zkrollups/setup:latest
    container_name: setup
    tty: true
    stdin_open: true
    env_file:
      - ./env/integration.env
  operator:
    image: docker.pkg.github.com/astarnetwork/zkrollups/operator:latest
    container_name: operator
    tty: true
    stdin_open: true
    env_file:
      - ./env/common.env
    volumes:
      - ./test/build:/contracts/build
    ports:
      - "3000:3000"
      - "3031:3031"
      - "3030:3030"
      - "8088:8088"
  prover:
    image: docker.pkg.github.com/astarnetwork/zkrollups/prover:latest
    container_name: prover
    tty: true
    stdin_open: true
    env_file:
      - ./env/common.env
  postgres:
    image: docker.pkg.github.com/astarnetwork/zkrollups/postgres:latest
    container_name: postgres
    tty: true
    stdin_open: true
    ports:
      - "5432:5432"
  ticker:
    image: matterlabs/dev-ticker:latest
    container_name: ticker
    ports:
      - "9876:9876"
